/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#pragma clang assume_nonnull begin
#pragma clang assume_nonnull end
#pragma clang assume_nonnull begin
#pragma clang assume_nonnull end
#pragma clang assume_nonnull begin
#pragma clang assume_nonnull end
struct _2_init_tigress_1_opaque_NodeStruct ;
union _4_MERGED_$node ;
struct __darwin_pthread_handler_rec ;
struct __sFILE ;
struct __sFILEX ;
struct __sbuf ;
struct _opaque_pthread_attr_t ;
struct _opaque_pthread_cond_t ;
struct _opaque_pthread_condattr_t ;
struct _opaque_pthread_mutex_t ;
struct _opaque_pthread_mutexattr_t ;
struct _opaque_pthread_t ;
struct timespec ;
struct timeval ;
struct _2_init_tigress_1_opaque_NodeStruct {
   struct _2_init_tigress_1_opaque_NodeStruct *prev ;
   struct _2_init_tigress_1_opaque_NodeStruct *next ;
   int data ;
};
extern int gettimeofday(struct timeval *tv , void *tz ) ;
typedef struct _opaque_pthread_attr_t __darwin_pthread_attr_t;
extern int pthread_cond_broadcast(struct _opaque_pthread_cond_t *cond ) ;
char **_global_argv  =    (char **)0;
typedef long long __int64_t;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
struct _opaque_pthread_attr_t {
   long __sig ;
   char __opaque[56] ;
};
typedef __darwin_pthread_attr_t pthread_attr_t;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
typedef struct _opaque_pthread_condattr_t __darwin_pthread_condattr_t;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
struct _opaque_pthread_mutex_t {
   long __sig ;
   char __opaque[56] ;
};
typedef struct _opaque_pthread_mutex_t __darwin_pthread_mutex_t;
typedef __darwin_pthread_mutex_t pthread_mutex_t;
struct _opaque_pthread_mutexattr_t {
   long __sig ;
   char __opaque[8] ;
};
typedef struct _opaque_pthread_mutexattr_t __darwin_pthread_mutexattr_t;
typedef __darwin_pthread_mutexattr_t pthread_mutexattr_t;
extern int __attribute__((__availability__(ios,introduced=2.0), __availability__(macos,introduced=10.4)))  pthread_mutex_init(pthread_mutex_t * __restrict   ,
                                                                                                                              pthread_mutexattr_t const   * _Nullable __restrict   ) ;
unsigned long _1_entropy  =    8823238296075986798UL;
typedef long __darwin_time_t;
struct timespec {
   __darwin_time_t tv_sec ;
   long tv_nsec ;
};
extern int ( /* format attribute */  printf)(char const   * __restrict    , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(struct _opaque_pthread_cond_t *cond ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_ptr_2  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
char **_global_envp  =    (char **)0;
typedef struct _opaque_pthread_t *__darwin_pthread_t;
extern int unlink(char const   *filename ) ;
typedef struct _opaque_pthread_cond_t __darwin_pthread_cond_t;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(struct _opaque_pthread_mutex_t *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
unsigned long _1_alwaysZero  =    0;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
struct __darwin_pthread_handler_rec {
   void (*__routine)(void * ) ;
   void *__arg ;
   struct __darwin_pthread_handler_rec *__next ;
};
extern int fprintf(struct __sFILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
int main(int argc , char **argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
char const   *_4_MERGED_$strings  =    "fac(%i)=%i\n\000fib(%i)=%i\n\000";
typedef struct __sFILE FILE;
__inline extern int ( __attribute__((__always_inline__)) __sputc)(int _c , FILE *_p ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
struct _opaque_pthread_t {
   long __sig ;
   struct __darwin_pthread_handler_rec *__cleanup_stack ;
   char __opaque[8176] ;
};
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_ptr_1  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
struct __sbuf {
   unsigned char *_base ;
   int _size ;
};
void MERGED(void *tigressRetVal , int n__0 , int whichBlock__7 ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
typedef __int64_t __darwin_off_t;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(struct _opaque_pthread_cond_t *cond , struct _opaque_pthread_cond_t *mutex ) ;
struct _opaque_pthread_condattr_t {
   long __sig ;
   char __opaque[8] ;
};
union _4_MERGED_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
struct _opaque_pthread_cond_t {
   long __sig ;
   char __opaque[40] ;
};
typedef __darwin_pthread_cond_t pthread_cond_t;
typedef __darwin_pthread_condattr_t pthread_condattr_t;
extern int __attribute__((__availability__(ios,introduced=2.0), __availability__(macos,introduced=10.4)))  pthread_cond_init(pthread_cond_t * __restrict   ,
                                                                                                                             pthread_condattr_t const   * _Nullable __restrict   )  __asm__("_pthread_cond_init")  ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
typedef struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_StructureType;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_list_1  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
void _5_stringEncoder(int n , char str[] ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   int tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
typedef __darwin_off_t fpos_t;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
typedef __darwin_pthread_t pthread_t;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int __swbuf(int  , FILE * ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern void *malloc(unsigned int size ) ;
extern int nanosleep(struct timespec  const  *__rqtp , struct timespec *__rmtp )  __asm__("_nanosleep")  ;
struct __sFILE {
   unsigned char *_p ;
   int _r ;
   int _w ;
   short _flags ;
   short _file ;
   struct __sbuf _bf ;
   int _lbfsize ;
   void *_cookie ;
   int (* _Nullable  _close)(void * ) ;
   int (* _Nullable  _read)(void * , char * , int  ) ;
   fpos_t (* _Nullable  _seek)(void * , fpos_t  , int  ) ;
   int (* _Nullable  _write)(void * , char const   * , int  ) ;
   struct __sbuf _ub ;
   struct __sFILEX *_extra ;
   int _ur ;
   unsigned char _ubuf[3] ;
   unsigned char _nbuf[1] ;
   struct __sbuf _lb ;
   int _blksize ;
   fpos_t _offset ;
};
extern int pthread_mutex_unlock(struct _opaque_pthread_mutex_t *mutex ) ;
extern int __attribute__((__availability__(ios,introduced=2.0), __availability__(macos,introduced=10.4)))  pthread_create(pthread_t __attribute__((__nullable__))  * _Nonnull __restrict   ,
                                                                                                                          pthread_attr_t const   * _Nullable __restrict   ,
                                                                                                                          void * _Nullable  (* _Nonnull  )(void * _Nullable   ) ,
                                                                                                                          void * _Nullable __restrict   ) ;
extern int atoi(char const   *s ) ;
unsigned int _2_init_tigress__opaque_array[30]  = 
  {      443,      292,      3,      43, 
        376,      5,      128,      390, 
        5,      213,      271,      7, 
        313,      446,      6,      318, 
        565,      10,      153,      670, 
        98,      383,      313,      12, 
        233,      502,      35,      478, 
        131};
extern int fseek(struct __sFILE *stream , long offs , int whence ) ;
extern int fscanf(struct __sFILE *stream , char const   *format  , ...) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_list_2  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
void megaInit(void) ;
void MERGED(void *tigressRetVal , int n__0 , int whichBlock__7 ) 
{ 
  char _4_MERGED_$locals[96] ;
  union _4_MERGED_$node _4_MERGED_$stack[1][32] ;
  union _4_MERGED_$node *_4_MERGED_$sp[1] ;
  void **_4_MERGED_$pc[1] ;
  void *_4_MERGED_$array[1][432]  = {{&& _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0,
                                      (void *)3UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)73UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0,
                                      (void *)5UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)1UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)24UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)4294967263UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)4294967261UL,
                                      && _4_MERGED__string$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__convert_void_star2void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)24UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)32UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)36UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__call$func_LIT_0, (void *)1UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)350UL,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0,
                                      (void *)3UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)95UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)40UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)44UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)44UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0,
                                      (void *)5UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)1UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)36UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)40UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)40UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)44UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)44UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)4294967251UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)4294967249UL,
                                      && _4_MERGED__string$result_STA_0$value_LIT_0,
                                      (void *)12UL, && _4_MERGED__convert_void_star2void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)48UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)56UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)40UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)60UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__call$func_LIT_0, (void *)2UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)246UL,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__formal$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0,
                                      (void *)3UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)234UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)40UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__call$func_LIT_0, (void *)3UL,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)72UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)64UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)64UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)64UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)64UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)64UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)64UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)4UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0,
                                      (void *)3UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)3UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)3UL, && _4_MERGED__goto$label_LAB_0,
                                      (void *)122UL, && _4_MERGED__call$func_LIT_0,
                                      (void *)4UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)88UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)80UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)10UL, && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_unsigned_long$left_STA_0$result_STA_0,
                                      && _4_MERGED__BXor_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_unsigned_long$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)10UL, && _4_MERGED__BOr_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__load_unsigned_long$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)10UL, && _4_MERGED__BOr_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__Mult_int_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)80UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)80UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)80UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)80UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)80UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__load_int$left_STA_0$result_STA_0,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                      && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)16UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)4294967164UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)4294967162UL,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)2UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)3UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_void_star$result_STA_0$value_LIT_0,
                                      (void *)0UL, && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)8UL, && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)3UL, && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1,
                                      && _4_MERGED__load_void_star$left_STA_0$result_STA_0,
                                      && _4_MERGED__global$result_STA_0$value_LIT_0,
                                      (void *)3UL, && _4_MERGED__store_void_star$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)20UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__constant_int$result_STA_0$value_LIT_0,
                                      (void *)1UL, && _4_MERGED__local$result_STA_0$value_LIT_0,
                                      (void *)44UL, && _4_MERGED__store_int$left_STA_0$right_STA_1,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)3UL,
                                      && _4_MERGED__goto$label_LAB_0, (void *)1UL,
                                      && _4_MERGED__returnVoid$}};

  {
  _4_MERGED_$sp[0] = _4_MERGED_$stack[0];
  _4_MERGED_$pc[0] = _4_MERGED_$array[0];
  goto *(*(_4_MERGED_$pc[0]));
  Lab_2000003: /* CIL Label */ ;
  _4_MERGED__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_int = (_4_MERGED_$sp[0] + 0)->_int < (_4_MERGED_$sp[0] + -1)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__string$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(_4_MERGED_$strings + *((int *)_4_MERGED_$pc[0]));
  (_4_MERGED_$sp[0]) ++;
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__load_void_star$left_STA_0$result_STA_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 0)->_void_star = *((void **)(_4_MERGED_$sp[0] + 0)->_void_star);
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_int = (_4_MERGED_$sp[0] + 0)->_int == (_4_MERGED_$sp[0] + -1)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_int = (_4_MERGED_$sp[0] + -1)->_int + (_4_MERGED_$sp[0] + 0)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__returnVoid$: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  return;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__constant_void_star$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 1)->_void_star = *(_4_MERGED_$pc[0]);
  (_4_MERGED_$sp[0]) ++;
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__load_unsigned_long$left_STA_0$result_STA_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_4_MERGED_$sp[0] + 0)->_void_star);
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__global$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  switch (*((int *)_4_MERGED_$pc[0])) {
  case 2: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& _2_init_tigress_1_opaque_ptr_1);
  break;
  case 3: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& _2_init_tigress_1_opaque_ptr_2);
  break;
  case 0: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& _2_init_tigress_1_opaque_list_1);
  break;
  case 1: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& _1_entropy);
  break;
  }
  (_4_MERGED_$sp[0]) ++;
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__store_void_star$left_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  *((void **)(_4_MERGED_$sp[0] + 0)->_void_star) = (_4_MERGED_$sp[0] + -1)->_void_star;
  _4_MERGED_$sp[0] += -2;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__MinusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_unsigned_long = (_4_MERGED_$sp[0] + 0)->_unsigned_long - (_4_MERGED_$sp[0] + -1)->_unsigned_long;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__formal$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  switch (*((int *)_4_MERGED_$pc[0])) {
  case 0: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& tigressRetVal);
  break;
  case 1: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& n__0);
  break;
  case 2: 
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(& whichBlock__7);
  break;
  }
  (_4_MERGED_$sp[0]) ++;
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__store_int$left_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  *((int *)(_4_MERGED_$sp[0] + 0)->_void_star) = (_4_MERGED_$sp[0] + -1)->_int;
  _4_MERGED_$sp[0] += -2;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__call$func_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  switch (*((int *)_4_MERGED_$pc[0])) {
  case 1: 
  printf(*((char const   * __restrict  *)(_4_MERGED_$locals + 24)), *((int *)(_4_MERGED_$locals + 32)),
         *((int *)(_4_MERGED_$locals + 36)));
  break;
  case 3: 
  *((void **)(_4_MERGED_$locals + 72)) = malloc(sizeof(struct _2_init_tigress_1_opaque_NodeStruct ));
  break;
  case 4: 
  *((void **)(_4_MERGED_$locals + 88)) = malloc(sizeof(struct _2_init_tigress_1_opaque_NodeStruct ));
  break;
  case 2: 
  printf(*((char const   * __restrict  *)(_4_MERGED_$locals + 48)), *((int *)(_4_MERGED_$locals + 56)),
         *((int *)(_4_MERGED_$locals + 60)));
  break;
  }
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__local$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 1)->_void_star = (void *)(_4_MERGED_$locals + *((int *)_4_MERGED_$pc[0]));
  (_4_MERGED_$sp[0]) ++;
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__branchIfTrue$expr_STA_0$label_LAB_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  if ((_4_MERGED_$sp[0] + 0)->_int) {
    _4_MERGED_$pc[0] += *((int *)_4_MERGED_$pc[0]);
  } else {
    (_4_MERGED_$pc[0]) ++;
  }
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_int = (_4_MERGED_$sp[0] + -1)->_int * (_4_MERGED_$sp[0] + 0)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__BXor_unsigned_long_int2unsigned_long$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_unsigned_long = (_4_MERGED_$sp[0] + 0)->_unsigned_long ^ (_4_MERGED_$sp[0] + -1)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__Le_int_int2int$right_STA_0$result_STA_0$left_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_int = (_4_MERGED_$sp[0] + -1)->_int <= (_4_MERGED_$sp[0] + 0)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__goto$label_LAB_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  _4_MERGED_$pc[0] += *((int *)_4_MERGED_$pc[0]);
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__Mult_int_unsigned_long2int$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_int = (_4_MERGED_$sp[0] + 0)->_int * (_4_MERGED_$sp[0] + -1)->_unsigned_long;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__PlusPI_void_star_int2void_star$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_void_star = (_4_MERGED_$sp[0] + 0)->_void_star + (_4_MERGED_$sp[0] + -1)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__constant_int$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 1)->_int = *((int *)_4_MERGED_$pc[0]);
  (_4_MERGED_$sp[0]) ++;
  (_4_MERGED_$pc[0]) ++;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__convert_void_star2void_star$left_STA_0$result_STA_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 0)->_void_star = (_4_MERGED_$sp[0] + 0)->_void_star;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__PlusA_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_unsigned_long = (_4_MERGED_$sp[0] + 0)->_unsigned_long + (_4_MERGED_$sp[0] + -1)->_unsigned_long;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__load_int$left_STA_0$result_STA_0: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + 0)->_int = *((int *)(_4_MERGED_$sp[0] + 0)->_void_star);
  goto *(*(_4_MERGED_$pc[0]));
  _4_MERGED__BOr_unsigned_long_int2unsigned_long$right_STA_0$result_STA_0$left_STA_1: /* CIL Label */ ;
  (_4_MERGED_$pc[0]) ++;
  (_4_MERGED_$sp[0] + -1)->_unsigned_long = (_4_MERGED_$sp[0] + -1)->_unsigned_long | (_4_MERGED_$sp[0] + 0)->_int;
  (_4_MERGED_$sp[0]) --;
  goto *(*(_4_MERGED_$pc[0]));
}
}
void _5_stringEncoder(int n , char str[] ) 
{ 
  int encodeStrings_i3 ;

  {
  encodeStrings_i3 = 0;
  switch (n) {

  }
}
}
int main(int argc , char **argv , char **_formal_envp ) 
{ 
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = argc;
  _global_argv = argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1L + (int )((((_1_alwaysZero & (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL)))) * (_1_alwaysZero | (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL)))) + (_1_alwaysZero & ~ (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL)))) * (~ _1_alwaysZero & (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL))))) ^ 0) + ((((_1_alwaysZero & (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL)))) * (_1_alwaysZero | (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL)))) + (_1_alwaysZero & ~ (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL)))) * (~ _1_alwaysZero & (((_1_entropy + 10) + 1UL) + ((- _1_entropy - 1UL) | (- 10 - 1UL))))) & 0) << 1UL));
  MERGED((int )((long )(_2_init_tigress__opaque_array[((unsigned int )(((_1_entropy - 1) + ((long )(_1_entropy - 1) >> 63L)) ^ ((long )(_1_entropy - 1) >> 63L)) % 10) * 3 + 0] % _2_init_tigress__opaque_array[5]) + -3L),
         argc, (int )((long )(_2_init_tigress__opaque_array[((unsigned int )(((_1_entropy ^ 9) + ((long )(_1_entropy ^ 9) >> 63L)) ^ ((long )(_1_entropy ^ 9) >> 63L)) % 10) * 3 + 0] % _2_init_tigress__opaque_array[5]) + -1L));
  MERGED(0L + (int )((((_1_alwaysZero & (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4))) * (_1_alwaysZero | (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4))) + (_1_alwaysZero & ~ (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4))) * (~ _1_alwaysZero & (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4)))) | 0) + (((_1_alwaysZero & (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4))) * (_1_alwaysZero | (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4))) + (_1_alwaysZero & ~ (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4))) * (~ _1_alwaysZero & (((_1_entropy | 4) << 1UL) - (_1_entropy ^ 4)))) & 0)),
         10L + (int )((((_1_alwaysZero & (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) * (_1_alwaysZero | (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) + (_1_alwaysZero & ~ (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) * (~ _1_alwaysZero & (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL))))) ^ 0) + ((((_1_alwaysZero & (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) * (_1_alwaysZero | (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) + (_1_alwaysZero & ~ (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) * (~ _1_alwaysZero & (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL))))) & 0) + (((_1_alwaysZero & (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) * (_1_alwaysZero | (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) + (_1_alwaysZero & ~ (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)))) * (~ _1_alwaysZero & (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL))))) & 0))),
         (_2_init_tigress_1_opaque_ptr_1 != _2_init_tigress_1_opaque_ptr_2) - (_2_init_tigress_1_opaque_ptr_1 != _2_init_tigress_1_opaque_ptr_2));
  MERGED((_2_init_tigress_1_opaque_ptr_1 == _2_init_tigress_1_opaque_ptr_2) + (_2_init_tigress_1_opaque_ptr_1 == _2_init_tigress_1_opaque_ptr_2),
         (int )((long )(_2_init_tigress__opaque_array[((unsigned int )((_1_entropy + 7) - (((_1_entropy + 7) << 1UL) & ((long )(_1_entropy + 7) >> 63L))) % 10) * 3 + 1] % _2_init_tigress__opaque_array[11]) + 5L),
         (_2_init_tigress_1_opaque_ptr_1 == _2_init_tigress_1_opaque_ptr_2) + (_2_init_tigress_1_opaque_ptr_1 != _2_init_tigress_1_opaque_ptr_2));
  return (0L + (int )((((_1_alwaysZero & ((_1_entropy ^ 6) - ((~ _1_entropy & 6) + (~ _1_entropy & 6)))) * (_1_alwaysZero | ((_1_entropy ^ 6) - ((~ _1_entropy & 6) + (~ _1_entropy & 6)))) + (_1_alwaysZero & ~ ((_1_entropy ^ 6) - ((~ _1_entropy & 6) + (~ _1_entropy & 6)))) * (~ _1_alwaysZero & ((_1_entropy ^ 6) - ((~ _1_entropy & 6) + (~ _1_entropy & 6))))) - ~ 0) - 1UL));
}
}
void megaInit(void) 
{ 


  {

}
}
__inline extern int ( __attribute__((__always_inline__)) __sputc)(int _c , FILE *_p ) 
{ 
  unsigned char *tmp ;
  unsigned char tmp___0 ;
  int tmp___1 ;

  {
  (_p->_w) --;
  if (_p->_w >= 0) {
    tmp = _p->_p;
    (_p->_p) ++;
    tmp___0 = (unsigned char )_c;
    *tmp = tmp___0;
    return ((int )tmp___0);
  } else
  if (_p->_w >= _p->_lbfsize) {
    if ((int )((char )_c) != 10) {
      tmp = _p->_p;
      (_p->_p) ++;
      tmp___0 = (unsigned char )_c;
      *tmp = tmp___0;
      return ((int )tmp___0);
    } else {
      tmp___1 = __swbuf(_c, _p);
      return (tmp___1);
    }
  } else {
    tmp___1 = __swbuf(_c, _p);
    return (tmp___1);
  }
}
}
